name: NetworkManager Fix
version: "1.1.0"
slug: network_manager_fix
description: Fix NetworkManager configuration for mDNS to prevent flooding caused by reflectors across multiple vlans
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/sle118/addons-network-manager-fix/tree/main/network-manager-fix
full_access: true
host_dbus: true
host_network: true
options: {}
schema: {}
hassio_api: true
hassio_role: manager
panel_icon: mdi:download-network
privileged: [NET_ADMIN, NET_RAW, PERFMON, SYS_ADMIN]
image: "ghcr.io/sle118/{arch}-addon-network-manager-fix"
options:
  primary_connection: ""
  sleep_time_seconds: 60

schema:
  primary_connection: "str"
  sleep_time_seconds: "int(30,300)"
